<script type="text/javascript" src="http://localhost/ampera2/style/js/jquery-2.2.0.min.js" ></script>
<script type="text/javascript" src="http://localhost/ampera2/style/jquery.datatable.js" ></script>
<script type="text/javascript" src="http://localhost/ampera2/style/js/bootstrap.js" ></script>
<script type="text/javascript" src="http://localhost/ampera2/style/responsive.datatable.js" ></script>
<script type="text/javascript" src="http://localhost/ampera2/style/datepicker/bootstrap-datepicker.id.min.js" ></script>
<script type="text/javascript" src="http://localhost/ampera2/style/datepicker/bootstrap-datepicker.js" ></script>
<script type="text/javascript" src="http://localhost/ampera2/style/datepicker/moment.js" ></script>
<script type="text/javascript" src="http://localhost/ampera2/style/tinymce/js/tinymce/jquery.tinymce.min.js" ></script>
<script type="text/javascript" src="http://localhost/ampera2/style/tinymce/js/tinymce/tinymce.min.js" ></script>